# Generated by Django 4.1 on 2022-08-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='data',
            new_name='date',
        ),
    ]
